### ISSUE TITLE
Move checkout to landing page

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-dashboard#10]
It might be possible to integrate the checkout iframe into our landing page. If it's possible we should do that rather than keeping it int the dashboard.

**Comment by Sjefkesuit** [comment]
Good news on this one as well. It is possible: [https://offeringcre.com/sign-up-1/](https://offeringcre.com/sign-up-1/)

I have to work a bit on the lay out but that should not be a problem. Also have to adjust the redirect to just be a thank you message but all of that is no problem. 2 for 2
