### ISSUE TITLE
Things to discuss Tuesday Jan 15

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#12]
List of things we should cover during our meeting> Might not even be that much but good to have it written out so we won't forget and we can also already think about it before getting together.

- [x] Client portal e-mail from Pabbly (If we enable auto subscribe it will overrule the e-mail that gets send and won't send the activation e-mail but only the invite to join portal dashboard e-mail, this is no good. Question is mainly how it works with the API, can we give them access through API without enabling it in the dashboard. I can explain) (Forwarding e-mail to you @m-ke in the mean time so we can go over it) (Also asked them for change in feature so we can enable or disable that e-mail which they say they will add in a few weeks, lets see)
- [x] Trial expired e-mail (Where to link to?)
- [x] Add custom domain for backend emails
  - https://help.mailgun.com/hc/en-us/articles/202256730-How-do-I-pick-a-domain-name-for-my-Mailgun-account-
- [x] ....

**Comment by Sjefkesuit** [comment]
Trial expired: Send them to their CRE dashboard and include language in the e-mail that stipulates they should go to the link that sends them to manage their subscription

Client Portal: For time being set manually after people sign up (Sjef can do at the end of each day), that way the e-mail doesn't overlap with the activation e-mail up on sign up.

**Comment by Sjefkesuit** [comment]
Adding things here for Tuesday 15th (feel free to add additional items):

- [x] Adding validations to input fields that are not using b-field, b-input set up
- [x] Update on where things are regarding Google Maps integration
- [x] General update
- [x]  User shouldn't get activation email when they sign up for trial second time
- [x] Domain setup for emails didn't work

**Comment by m-ke** [comment]
Tuesday 22:

* Topics re:pdf app
  * property info the lines show only if value present
  * recent sales / rent comparables only show up if at least 1 unit present
  * what if they have no address? (currently address is optional) -> get back to Marion PDF app #8
  * rent comps table would be the same as recent sales - is that ok?
  * rent roll - make lines twice as thick because now they're tiny 
  * rent roll page only exists if at least 1 unit present)

Google maps api:
```  json:
   { error_message: 'This API project is not authorized to use this API.',
     results: [],
     status: 'REQUEST_DENIED' }
```

**Comment by m-ke** [comment]
OS questions:
  
  * can current/potential net operating income be negative?
  * can CAP rate be negative?
  * is the CAP rate calculation correct? this.currentNetOperatingIncome / this.property.price * 100

**Comment by Sjefkesuit** [comment]
1: Yes, net operating could be negative.
2: Yes, if operating income is negative this will be negative as well.
3: The calculation seems indeed correct. In example

1. Net Operating Income 50'000$
2. Property Price: $2'000'000 (2 million)
3. CAP rate: (50'000/2'000'000)= 0.025 * 100 = 2.5%
