### ISSUE TITLE
Password reset e-mail doesn't seem to be send

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#19]
The dashboard behaves as expected and shows the success message, however the e-mail never comes thru (tried using 2 different e-mail addresses)

**Comment by m-ke** [comment]
I checked the logs, it's because of the domain not being set (what we were trying to set last week), could you check ?

**Comment by Sjefkesuit** [comment]
Yes I checked. It wasn't working yet this morning but I changed the settings and now it seems to work. However might in this case indeed still take 24 or 48 hours before it starts actually working. But it is active and confirmed.

**Comment by Sjefkesuit** [comment]
Lets check again on Tuesday, by that time it should all work as expected.

**Comment by m-ke** [comment]
perfect, thanks for the update! the logs were saying before that it won't allow us to send the emails without the domain confirmed. hope it's all set by Tuesday! :)
