### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#22]
Just creating the issue so we have a place to start to collect them:

- [x] Pricing input field on Property Information screen is extremely small. Should be equal size to all other fields on this page
- [x] Valuation overview screen (basically the home screen): Adding more valuations messes with the lay out in a way that you can't read anything anymore. Should wrap after 4 or so I guess.

**Comment by m-ke** [comment]
closing this as we have the other issue open with adjustments that need to be made
