### ISSUE TITLE
Testing things

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#25]
Listing out items noted during testing

- [x] Added this to the css but pretty big thing is the Pricing input field in the Property Information section. Tiny box compared to the others.
- [x] At the moment you can't save a sales comparable without putting in the price (which makes sense) but the error message doesn't indicate that (I guess this is part of what we will fix on Sunday with verifications but just noting it down in case it is not)
- [x] When changing pricing on the O/S it gives an error (This is already known bug but adding it here so we can keep track of when it is solved)
- [x] Company logo upload doesn't work (Currently not showing on package anyway so could also choose to now enable for time being) (Same for Profile Picture)
- [ ] The first item on the Sales and Rent Comps Map view in the package should be the address of the Property from the package. Only starting at 1. should it be the rent comparables (Ideally this first one would have a different marker as well so it is clear that that is the property and you can distinguish it easily from the comparables). (Attached screenshot to make this clear)
<img width="769" alt="screenshot 2019-02-09 at 10 45 16" src="https://user-images.githubusercontent.com/33290928/52519186-d3e09b00-2c57-11e9-84b0-042c2ceaeaa4.png">
- [ ] The valuation overview page doesn't show the address of the property. Only shows New valuations. Makes it difficult to know what is what. It shows the address for a few seconds when opening and then it auto refreshes to show New Valuation instead. It also doesn't include the Price anymore after it does that refresh.

**Comment by m-ke** [comment]
OS not done yet, sales comp redirect now fixed

**Comment by m-ke** [comment]
leaving this open to add more stuff if need be.

**Comment by m-ke** [comment]
re: the last item: yes, exactly, we'll add the validations on Sunday along with the correct validation error messages.

**Comment by Sjefkesuit** [comment]
The Testing Doc: Feel free to change if applicable
https://docs.google.com/document/d/1mEtK1Qne9mvnzuiln9ysGLx-fEhNpd5MXWnteN34V88/edit

**Comment by m-ke** [comment]
Company updates are broken in the backend. I might do a hack fix later, or remove the section for now.

**Comment by m-ke** [comment]
re: the recent sales - to me it doesn't make sense to put the address of the property in the list of recent sales. Currently we have a red pin for the property & blue pins for comparables - we could add the address of the property somewhere, the list just doesn't seem appropriate to me
![image](https://user-images.githubusercontent.com/6909854/52522666-ab24c980-2c88-11e9-9bbb-a6b99c7bdbf1.png)

**Comment by Sjefkesuit** [comment]
@m-ke I fully see your point. I do however think we should show it on the same page (have to remember the people looking at this aren't looking at google maps etc every day). Would it be an option to place it above the Recent Sales header?

**Comment by m-ke** [comment]
@Sjefkesuit I removed the link to company settings since right now the backend is broken and I can't quickly fix it. We're not using the info anywhere as of now anyways so I'd suggest we re-add it in v1.1

**Comment by Sjefkesuit** [comment]
@m-ke fully agree with that approach.

**Comment by m-ke** [comment]
Made a separate issue for the last items here: https://github.com/cre-project/pdf-app/issues/20

Closing this to make it clearer what still needs to be done (ie separate issues for future bugs & adjustments)
