### ISSUE TITLE
Finish OS in dashboard

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-dashboard#27]
- [x] take rented units into account when calculating potential / current rent
- [x] save all fields when user saves the page
- [x] check that all calculations are correct
- [x] remove 'expenses' page

**Comment by m-ke** [comment]
@Sjefkesuit  I think I'll leave the calculation checking to you :angel:  I'm sure not all stuff's right (& I still have to add the checks that some of the calculations do not result in negative numbers)

**Comment by Sjefkesuit** [comment]
@m-ke thanks so much. Can definitely see the light at the end of the tunnel. The adding and removing line items works like a charm. Few issues so far that I do see:

- [x] First thing is that the amounts should be all times 12 from the unit mix. E.g. If total rent of all units in unit mix is $10K the gross potential rent should be $120K, not $10K as it is currently.
- [x] There is no line item for Other Income, nor the possibility to add one. 
- [x] Real estate tax percentage calculation is wrong: The resulting amount should be divided by 100 to get the correct amount. Currently 1% equals the Price.
- [x] Price per unit calculation on the side form isn't working, remains at 0
- [x] Get: Something went wrong error message when clicking save and next (500 error)
- [x] For Sjef: Check and change formatting from amounts on OS and Sales and Rent comparables. 

I can help on Sunday adding the validations. I actually thought I did that already back in the validation branch but maybe too much has changed.

**Comment by Sjefkesuit** [comment]
- [x] Management fee is also calculated incorrectly as 100% instead of 1%
