### ISSUE TITLE
Changes to Billing & Subscription Page under Settings

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#32]
A few to-do's

- [x] Open the window that opens after clicking the change button in a new window. Just so it is easier for user to close it and be back at their billing settings after making changes. Now very hard to get back. (looked into adding _blank myself but seems to be a bit more complicated than that as it is not a set link.

- [x] Add some text on the right hand side that explains that we are using a third party to guarantee security regarding payments and add a link to the pdf documentation that is currently here: https://drive.google.com/drive/u/1/folders/1uI0QIeKjjIOMQF259vZZHcPneItxiDeS

For text on the right I suggest we say:

As we want to make sure your payment information is save we are using a third party called Stripe as our trusted payment provider and aren’t storing any of your sensitive information ourselves. When you click Change on this page a new window will open which will give you the ability to change your billing and subscription information. You can follow the following documentation on how to change things (LINK HERE TO THE PDF). 

After you are done making your changes simply close the additional window and reload this page. After that you are good to go.

**Comment by m-ke** [comment]
@Sjefkesuit  how do you want to link the pdf? make it downloadable? redirect? open in an iframe?

**Comment by m-ke** [comment]
I made the change button open a new window, you should just be aware that it's super ugly if your browser is set to block popups (like mine) 
![popup](https://user-images.githubusercontent.com/6909854/52445929-d0042a00-2b2c-11e9-932d-46697a48408c.png)

**Comment by m-ke** [comment]
Hey @Sjefkesuit you can have a look. For now I linked the folder in Drive, we can discuss tomorrow where to put the docs and I'll change the link (I'd suggest on the landing page)
