### ISSUE TITLE
Valuation Overview auto-refreshes and deletes all information

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#34]
Issue:
Every time I click the Home button on top left it takes me to the correct page, the valuation overview.
All looks good for the first 4 seconds but after that every time it deletes all the information from each package.

What happens:
1. It replaces the address with New Valuation
2. It does no longer display Price in the black bar
3. When opening a package it doesn't contain any information 
4. When you click back to Home and click on the package within the first 4 seconds or so it opens and it does contain all the information.

**Comment by m-ke** [comment]
It doesn't do that for me... might just be reordering the valuations. let me see what happens if I order them by date updated

**Comment by m-ke** [comment]
The packages are now sorted by date updated & every time I navigate back & forth the order is the same & no data disappears. Closing this now, please re-check and let me know if it happens again & you can reliably reproduce it
