### ISSUE TITLE
Take out Pricing input from Property Info

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#38]
Issue:
Take out the Price field from the Property Information screen.

As per Sonny, this doesn't make any sense to have it there.
Only keep on the Side form in the Operating Statement and users will set it there.

(Ideally for time being we could just comment it out from the Property Information is that is all it takes)

**Comment by m-ke** [comment]
this one will have to be postponed to next version. we need the price to save the property. right now it would require a lot of refactoring to remove it

**Comment by m-ke** [comment]
For now:  remove field & set value to 0 when creating property
