### ISSUE TITLE
Operating Statement Fields don't show up sometimes

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#40]
Issues:
As we had before, sometimes up on loading first time the other income as well as most of the expense line items dont' show up.

**Comment by m-ke** [comment]
Incomes do not appear in the response from the server

**Comment by Sjefkesuit** [comment]
@m-ke both Sonny and I still experienced that up on first loading the Other Income line item does not appear. The expense line items seem to be working correctly now however.

**Comment by Sjefkesuit** [comment]
Testing now and other income line seems to be working. Will open issue again in case turns out with additional testing it isn't fixed (I am testing on https://cre-dashboard-testing.firebaseapp.com/#/package/5e61889c-0230-4184-a133-cdbab73751f2/operating-statement)
