### ISSUE TITLE
When clicking Home all address information changes

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#42]
Issue:
Same issue as before where after clicking home button after a few seconds everything changes to empty values.

Both me and Sonny have this same issue:

I have attached errors from the Console.
Might be related to issues from Google Tag Manager. If that is indeed the case feel free to take that all out for time being.

<img width="617" alt="screenshot 2019-02-14 at 19 56 21" src="https://user-images.githubusercontent.com/33290928/52810368-b154e480-3092-11e9-8a24-88d154cca86a.png">
<img width="617" alt="screenshot 2019-02-14 at 19 55 51" src="https://user-images.githubusercontent.com/33290928/52810369-b154e480-3092-11e9-84f6-fb6f5598017c.png">

**Comment by Sjefkesuit** [comment]
@m-ke I went ahead and already took out Tag Manager in case that was it. Even if not, doesn't really matter for now, lets first get it out without issues.

I can't test locally as forgot how to set local ENV so please double check my commits before deploying

**Comment by Sjefkesuit** [comment]
Adding screenshot of what it looks like. It still has the property picture but looses all other info. After reloading the screen it gets it back. 
<img width="1670" alt="screenshot 2019-02-14 at 20 28 57" src="https://user-images.githubusercontent.com/33290928/52812218-44901900-3097-11e9-86ad-bae53625e3aa.png">


Steps to recreate:
1. Open any package
2. Click away from property information to a next step (doesn';t matter which one, could be preview even)
3. Click on the home button
4. Wait 4 seconds

All information dissapears.

**Comment by m-ke** [comment]
@Sjefkesuit  Marion said she pushed some changes that may have fixed it. Have you re-checked since Friday?

**Comment by m-ke** [comment]
I'm assuming this was no longer an issue since you moved it to done @Sjefkesuit?

**Comment by Sjefkesuit** [comment]
Yes this seems to have been fixed and is working as expected now
