### ISSUE TITLE
Dashboard does not refresh when new user signs up

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#46]
Issue:
I was logged on as Donald Duck.
I then went to offeringcre.com and signed up with a new user.
Clicked on activation in the activation e-mail
After setting password this did not bring me back to log in but kept me logged on as Donald Duck.
I then logged out and logged on as the new user.
This worked, however I still see the home screen and packages from Donald Duck even tho under settings I see the new e-mail.

We had this issue before. 

Not sure if this would even be an issue for our users if they only have 1 account, but if they end up signing up with more than 1 as well it obviously should not happen that you see packages from someone else in your account.

**Comment by m-ke** [comment]
I'll call logout when a user accesses activation page.
