### ISSUE TITLE
User Settings doesn't show the Subscription Name

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#48]
Under Billing and Subscription settings it states:

<img width="297" alt="screenshot 2019-02-23 at 15 52 23" src="https://user-images.githubusercontent.com/33290928/53287961-0bd0fd80-3783-11e9-9dbc-9d7fdf4d3f1a.png">

Even when on a Trial subscription. Not a big problem when on trial but if they are on a paying it should at least tell them what their subscription is ideally.

**Comment by m-ke** [comment]
fixed in https://github.com/cre-project/cre-dashboard/commit/bbe8fcfcbe42d299be3cc91754ed9570b97ed256
