### ISSUE TITLE
Implement Pricing Solution

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#5]
Need to set up all that is needed to be able to accept payments and give users ability to make changes to their subscriptions.

@m-ke lets discuss but wanted to open the issue as it might also be applicable to how we set up our user authentication. 

Best options with our budget and our needs seems to be Pabbly: [https://www.pabbly.com/subscriptions/api/#](https://www.pabbly.com/subscriptions/api/#)

**Comment by m-ke** [comment]
@Sjefkesuit We should have a look at the checkout form they offer to see how to seamlessly integrate it. I tried to add it to our dashboard and it doesn't feel very integrated- it feels too much like a completely different website so I'm inclined to think people wouldn't trust it much (but I might be wrong)

**Comment by m-ke** [comment]
The issue is that they have a background there.. this is what it looks like if I use a smaller size for the iframe 
![image](https://user-images.githubusercontent.com/6909854/50255962-7026b800-03f4-11e9-8d8c-268b2a688519.png)

and this if I just fill the whole page with the form 
![image](https://user-images.githubusercontent.com/6909854/50256024-c4319c80-03f4-11e9-97d2-abe37cfab59d.png)

**Comment by Sjefkesuit** [comment]
You can change the settings and get rid of the background. That should help.

Let's look over lunch today

**Comment by Sjefkesuit** [comment]
I changed the setting to take out the background picture. This should be the Iframe from the two plans we have:

Small: Great
<iframe src=”https://payments.pabbly.com/subscribe/5c164cdf1d8f824f9a8cc82e/great-plan-jan-2019” width=”1000″ height=”1000″>
</iframe>

Medium: Better
<iframe src=”https://payments.pabbly.com/subscribe/5c164d881d8f824f9a8cc830/better-plan-jan-2019” width=”1000″ height=”1000″>
</iframe>

In the Pabbly dashboard under settings we can change other things as well as needed.

**Comment by Sjefkesuit** [comment]
@m-ke , both options we discussed are possible:

1: This is preferred as this starts everybody off on a trial for 1 week and does not require them to enter credit card information when signing up (we do have to think about a nice UI to get them to upgrade. Pabbly does send out an automatic e-mail when subscription is about to expire so we can use those as touch points at the beginning):

<iframe src=”https://payments.pabbly.com/subscribe/5c1bbc8a2abc0f049777ded6/trial” width=”1000″ height=”1000″> </iframe>

2: They allow for embedding the checkout page where you have to choose the type of subscription (not in a nice way with features but at least it is possible) (they actually only allow to choose from different plans from the same product (which normally would be used to choose from annual or monthly billing, but I think we actually don't need this if we start people of on a trial anyway): 

<iframe src=”https://payments.pabbly.com/checkout/5c1bbcc92abc0f049777ded7” width=”1000″ height=”1000″> </iframe>

**Comment by m-ke** [comment]
Closing this as we have decided on implementation and split this up into separate tasks.
