### ISSUE TITLE
Missing Ability to Edit and/or Delete Sales and Rent Comparables

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/cre-dashboard#6]
Recreate:
1. Add a Sales or Rent Comparable.
2. After adding it you will see it in the list of comparables

Actual:
1. There is no edit button
2. You can manually edit information within the line item but that is not very clear and it does not get saved.

Expect:
1. Expect to see the corresponding line item and an Edit button.
2. When clicking the edit button you expect to see a similar drop down as while adding a new comparable but with the available information already filled out.
3. Ideally any other sales comparables in the list would "move down" so it creates spaces for the input fields for the one selected to be edited. 

4. Also expect to have the garbage bin icon that would delete a line item.

**Comment by Sjefkesuit** [comment]
@m-ke I am telling Hristian that we will fix these issues so he can focus on Preview and Export (assuming his quote makes sense)

**Comment by m-ke** [comment]
This is now implemented in full.

**Comment by sjeftijssen** [comment]
Awesome. Anything you can push already?
