### ISSUE TITLE
Create user activation email

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-dashboard#8]
Check in pabbly whether we can get the customer id and use it in the email.

If so, we'd send the activation link from pabbly directly rather than from the web server.

The email should contain a link to activation page:

`https://cre-dashboard-testing.firebaseapp.com/#/activate/<customer_id>`

**Comment by Sjefkesuit** [comment]
Unfortunately it doesn't seem that it is possible to add the customer id field to the Pabbly standard e-mails. However I have contacted their support to make sure that is indeed the case. To be continued....

**Comment by Sjefkesuit** [comment]
Update on this: I heard back from Pabbly and as I thought it is indeed not possible at this point in time. However, they also immediately mentioned that it is not a difficult thing to add and they will do it in their next release that is scheduled for in 10 days from now. Which means I think we should wait to see if that indeed happens as that would be by far the easiest thing (would leave it a lot easier to customise messaging etc). 

I asked them to let me know in case the 10 day timeframe changes for some reason so we have enough time to work on setting it up from server directly if need be.

Can we assume it will work and still test activation etc in the mean time?

**Comment by Sjefkesuit** [comment]
Waiting on the ID property but everything else is set up. You can see the e-mail when you go to our landing page and sign up for the trial.
