### ISSUE TITLE
Link to pabbly customer portal from user settings

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-dashboard#9]
* make a request to backend to get a URL so that users don't have to log in separately
* redirect users to the resulting URL

https://www.pabbly.com/subscriptions/api/#section29

**Comment by Sjefkesuit** [comment]
Ideally we would send them directly to the subscription edit section at this link:

https://payments.pabbly.com/portal/app/offeringcre/subscription-edit/<CustomerId>

**Comment by Sjefkesuit** [comment]
Open Questions:

1. Can we set the URL we would like to send them to? Is it possible to send them directly to subscription-edit section?
